[snowflake]
account = "BGAKJDJ-KK79102"
user = "SHASHANKSHAGA"
api_key = "eyJraWQiOiIxMDQ2NDE3NDA5MyIsImFsZyI6IkVTMjU2In0.eyJwIjoiNDA4NzU1MjQ6NDA4NzU1MjQiLCJpc3MiOiJTRjozMDA0IiwiZXhwIjoxNzczMDM0NjA2fQ.1Yd2vDf5o49xP0vlbBmuLg2h3_coGCib9g5LJQclkM4FgEspdoQOuxwd_jSLhghF1P2dlv65tLkMDhXRJkm9Tg"
role = "ACCOUNTADMIN"
host = "BGAKJDJ-KK79102.snowflakecomputing.com"